version: '3'

services:
  web:
    restart: always
    build: .
    command: bash -c "python manage.py migrate --noinput && python populate.py && python manage.py runserver 0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - redis:redis
  appschedule:
    build: .
    command: python run.py
    volumes:
     - .:/app
    depends_on:
     - redis
    links:
      - redis:redis
  dramatiq:
    build: .
    command: dramatiq core.tasks
    volumes:
     - .:/app
    depends_on:
     - redis
    links:
      - redis:redis
  redis:
    restart: always
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data


