# Generated by Django 3.2 on 2021-04-24 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_follow_followentry"),
    ]

    operations = [
        migrations.RenameModel(old_name="FollowEntry", new_name="ReadedEntry"),
        migrations.AlterField(
            model_name="feed",
            name="last_fetch",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="feed", name="url", field=models.URLField(unique=True)
        ),
    ]
