# Generated by Django 3.2 on 2021-04-24 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210424_0416'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readedentry',
            unique_together={('user', 'entry')},
        ),
    ]
