# Generated by Django 3.2 on 2021-04-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_alter_readedentry_entry")]

    operations = [
        migrations.AlterField(
            model_name="entry", name="raw", field=models.TextField(unique=True)
        )
    ]
